const Blog = require('../models/Blog');

const blogs = [
  {
    user_id: 1,
    date_created: 2022 - 07 - 27,
    blog_title: 'Am I an Idiot for Wanting a Dumber Phone?',
    blog_description:
      'WIRED’s spiritual advice columnist offers counsel to a reader overwhelmed by apps, dings, and beeps.',
    Blog_text:
      'As more and more of the formerly mute objects in our lives (refrigerators, thermostats, doorbells, even toilets) are christened “smart,” it often feels as though the entire inanimate world were undergoing a process of enlightenment. And “smart” is a difficult adjective to resist, particularly in a society that regards intelligence as a form of currency—or even, at times, a spiritual virtue. So while “dumbing down” one’s phone ostensibly describes a rather mundane process of removing apps, blocking internet access, and choosing unappealing aesthetic features (gray scale, bland wallpaper), I understand the anxiety it can provoke. It’s hard to avoid feeling that such digital minimalism is swimming against the current of this awakening,that you are not just simplifying your life but also downgrading your mind.',
    'Perhaps that’s why one of the most popular new-generation dumb phones, the Light Phone, opts for the language of luminosity and its association with intellectual brilliance. The original model, whose capacities were limited to making and receiving calls, was described in the company’s 2015 Kickstarter as “thoughtfully simple” and promised a life in which users could engage more fully in cerebral and artistic tasks, the pursuits of the higher mind, without those buzzes and beeps that prompt a craving for the next dopamine rush. But the story of the Light Phone also illustrates the backsliding familiar to anyone who’s attempted a digital paring down—the way features, almost on their own, creep back into the picture. By the time the second model was released, in 2019, the phone had added a (black-and-white) touchscreen and text messaging, plus music, mapping, and ride-sharing apps. The promotional materials stress that these additions are “tools not feeds,” a justification that had the rather dubious ring of a dieter insisting that their indulgences are composed of “good fat.”':
      'Even the most zealous attempts to renounce ubiquitous technologies devolve into rationalization and the invention of creative loopholes. I happen to know a woman who was such an inveterate news junkie that she deleted all media apps and browsers from her phone, stripping it down to the bedrock of text, calls, weather, and maps—a solution that worked until she discovered it was possible to locate the New York Times Company’s headquarters in Manhattan on Google Maps and access the paper’s homepage through the app’s internal browser. The old saw about addictions—that they are impossible to outsmart—applies doubly to smart technologies, which are engineered to be used compulsively and elude your most ingenious efforts to gain mastery over them.',
    'With that in mind, I might suggest a more counterintuitive solution: Stop fighting the fear of dumbness and instead embrace it. Like most people who want to “go dumb,” I assume that you’re attracted in part to the term’s association with silence—the desire to dial down the chatter—but unsettled by some of its more unflattering synonyms, like idiocy. But idiocy was not always weighted by the negative associations it now carries. The word stems from the Greek idiotes, which referred to Athenians who were essentially laypersons—those who, unlike soldiers, scribes, and politicians, maintained little connection to the affairs of the state. It meant “on one’s own” or “private” (meanings that persist in words like idiosyncratic) and was reserved for those who enjoyed a freedom and autonomy from public life, the kind of existence that often serves as a haven for independent thought. Gilles Deleuze argued that idiocy was intimately linked to philosophy, beginning with Socrates, who famously recognized that he “knew nothing” and claimed this made him wiser than those who believed themselves intelligent. Descartes, in order to plant modern thought on a new terrain, similarly willed himself to disown all the knowledge he’d long taken for granted.':
      'Few of those positive connotations survive today, and yet the resurgent nostalgia for dumb technologies is often spurred by a not entirely modern desire to distance oneself from the bustle of the polis and the frenzied commerce of the agora. Perhaps this is just another way of saying that, despite the widespread celebration of smartness, many of us secretly long to know less. The notion that information at a certain scale becomes something less than informative was a truth colorfully voiced by Thoreau, whose complaints about the 19th-century news cycle read as surprisingly familiar today. When he heard that a transatlantic cable line would soon bring updates from Europe, Thoreau imagined “the first news that will leak through into the broad, flapping American ear will be that Princess Adelaide has the whooping cough.” The suspicion that such “knowledge” was making him denser was partly what spurred him to abandon the city for Walden. And I sense in your question, Dumbstruck, a similar inkling that the information economy obscures, somewhere—perhaps in the fine print of its mammoth user agreements?—a bleaker existential bargain: that the instant access to knowledge has subtly atrophied your imaginative musculature; that your immersion in digital echo chambers might be foreclosing more original forms of thought.',
    'Idiocy should not be confused with stupidity, the willful refusal of information that might disrupt one’s rigid convictions. The latter is rooted in a pride that makes it the inversion of smartness, not its alternative. Idiocy might be seen as a condition of openness and flexibility, qualities that define the fool archetype that appears in many cultures, from the Sioux heyoka, a sacred clown who deliberately engaged in counterintuitive actions (riding a horse backward, wearing clothes inside out, complaining of being full when food is scarce) so as to challenge popular assumptions, to the Russian yurodivy, or holy fool, a figure whose seeming madness was believed to lend him divine insight. Fools tend to be shape-shifters who thrive at thresholds and boundaries. This was particularly true of the Shakespearean fool, who was frequently “balancing on the edge between reality and various constructions of reality,” as one scholar puts it. The fool mediated the space between the play and the audience—that dimension where the virtual meets the real—moving fluidly between the stage and the crowd and occasionally breaking the fourth wall to comment on the play’s themes.':
      'I bring up the fool in part to stress the virtue of “dumbing down” as opposed to opting out. As appealing as it might be to live totally off the grid or leave civilization, it’s practically impossible to emulate Thoreau’s retreat to Walden (as impossible as it was even for Thoreau himself). It may well be that the dumbed-down smartphone offers a distinct advantage: Even the barest smartphones can be restored to their full capabilities at any moment, which places the user in the fool’s liminal space, a no-man’s-land that might offer perspective, or even wisdom. Your unwillingness to “take the plunge,” as you put it, seems less a sign of fearful waffling than evidence that you long for those unique possibilities that exist somewhere between the online and off, between the virtual and the real. In the best-case scenario, the stripped-down smartphone offers neither an escape from reality nor a refusal of its conditions, but a portal into new opportunities for defining one’s relationship to public life—while still being able to call an Uber.',
    cover_image_url:
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS9gMZCoLAgQD0wQ_gUX04G67XB-6BW-E5jOg&usqp=CAU',
  },

  {
    user_id: 2,
    date_created: 2022 - 07 - 20,
    blog_title:
      'No NFTs in Minecraft? This Crypto Group Will Make Its Own Game',
    blog_description:
      'In the battle over digital ownership, both NFT Worlds and Microsoft-owned Mojang claim to be putting players first.',
    Blog_text:
      'ON JUNE 20, Microsoft-owned Mojang announced that NFTs and blockchain technology would no longer be allowed to “integrate” with Minecraft. That was bad news for NFT Worlds, which has spent months building an entire crypto-economy on top of a collection of the randomized seeds needed to make specific Minecraft maps.Now, the team behind NFT Worlds announced it will create a new game thats based on many of the core mechanics of Minecraft but which will be “completely untethered from the policy enforcement Microsoft and Mojang have over Minecraft.” NFT Worlds promises its new Minecraft-style game will be built “from the ground up” to be familiar to Minecraft players, but now with the modernization and active development Minecraft has been missing for years.Don’t Worry, Everything’s Gonna Work Out Just Fine NFT Worlds’ game will always be free to play, the team says, and users won’t need a credit card to purchase any additional content. That content will presumably be purchased instead with the NFT Worlds token, whose value has plummeted over 60 percent in a week following Mojang’s announcement. For the time being, players that own an NFT world issued by NFT Worlds can still use its random seed to play in Minecraft or even host multiplayer sessions in that map, as a Microsoft spokesperson confirmed to Vice. But that’s not saying much, since the NFT itself never provided exclusive rights to that map any more than writing “World 1-1” on a piece of paper provides ownership rights to the iconic Super Mario Bros. level. Under Microsoft’s new rules, though, NFT Worlds blockchain will no longer be able to hook into Minecraft’s API. That means that players can no longer easily make in-game crypto payments denominated in NFT Worlds’ $WRLD token, as well as take advantage of other features coded using the NFT Worlds API. The NFT Worlds team says that it will prioritize “backwards compatibility with existing Minecraft server development plugins and practices” in its upcoming clone. That means creators should “continue building NFT Worlds content” on top of Minecraft, the team says, confident that it will work with the new, rebranded NFT Worlds game whenever it launches.',
    cover_image_url:
      'https://news.microsoft.com/wp-content/uploads/prod/sites/68/2016/11/minecraft1-6-4-1920x1080-png2-1-960x640.png',
  },

  {
    user_id: 3,
    date_created: 2022 - 07 - 10,
    blog_title: 'Review: HP Dev One Linux Laptop',
    blog_description:
      'Even if you’re not a developer, this reasonably priced, user-repairable Linux laptop from HP has plenty of attractive features.',
    Blog_text:
      "HP'S LATEST LINUX laptop sees the computer maker collaborating with erstwhile competitor (or at least, fellow Linux laptop maker) System76. It seems like an odd combo, given that System76 makes its own competing laptops, but the collaboration works.The Dev One is a very nice Linux machine that packs enough punch for developers or creatives without hitting top-tier laptop prices. Even more impressive is the work HP and System76 have put into making Linux work perfectly with the AMD chipset.Combining HP's hardware capabilities and industry experience with System76's Pop!_OS desktop has produced the best all-around Linux laptop you can buy right now. HP Hardware In a refreshing change from how most laptops are sold these days, there is only one model of the Dev One. Another nice touch is that it gets a dedicated website, which makes ordering simple. Dell, are you listening? The Dev One costs $1,100, which gets you a 14-inch laptop with a 1,000-nit 1080p screen, an AMD Ryzen 7 5850 chip, integrated Radeon graphics, 16 gigabytes of RAM, and a 1-terabyte NVMe M.2 2280 SSD. The RAM and SSD are user-upgradable (RAM support caps at 64 gigabytes). Getting into the components is simple. There are just five screws between you and any upgrades you want to make. The nearest Windows version of this same laptop gets a 9 out of 10 on iFixit's repairability scale. As the name suggests, the Dev One is aimed at the developer audience, much like Dell's XPS 13 Developer Edition. Despite the names though, these are really just laptops with Linux preinstalled. The Dev One will work well for almost any task, developer-related or otherwise. Don't let the word 'developer' in the name deter you if you're not one. That said, I did put the Dev One through some developer-type tasks. I set up a Python development environment, which was no trouble, thanks to the extensive repositories Pop!_OS offers, and I ran benchmark tests geared toward developer tasks (i.e., CPU- and RAM-intensive tasks). The Dev One worked well for all these things. It was no slouch at editing 4K video either, thanks to that AMD chip. If benchmarks are your thing, have a look at the tests Phoronix posted on OpenBenchmarking.org. The results are impressive. The Dev One runs circles around many of its Intel-based competitors.",
    cover_image_url:
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTlWR4rGltZX7uvkRAZvyM5BLeeB9REveOIMA&usqp=CAU',
  },
];

const seedBlogs = async () => {
  await Blog.destroy({
    where: {},
  });
  await Blog.bulkCreate(blogs);

  console.log('✅ Blogs');
};

module.exports = seedBlogs;
